/*
 *
 * HomePage constants
 *
 */

export const DEFAULT_ACTION = "app/HomePage/DEFAULT_ACTION";
export const CHANGE_STORE_DATA = "app/HomePage/CHANGE_STORE_DATA";

export const SAVE_BOOKING_DATA = "app/HomePage/SAVE_BOOKING_DATA";
export const RESET_BOOKING_DATA = "app/HomePage/RESET_BOOKING_DATA";

export const LOGOUT_APP = "app/HomePage/LOGOUT_APP";
export const LOGOUT_APP_SUCCESS = "app/HomePage/LOGOUT_APP_SUCCESS";
export const LOGOUT_APP_ERROR = "app/HomePage/LOGOUT_APP_ERROR";

export const GET_CATEGORY = "app/HomePage/GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "app/HomePage/GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "app/HomePage/GET_CATEGORY_ERROR";

export const GET_SUB_CATEGORY = "app/HomePage/GET_SUB_CATEGORY";
export const GET_SUB_CATEGORY_SUCCESS = "app/HomePage/GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_ERROR = "app/HomePage/GET_SUB_CATEGORY_ERROR";

export const GET_VEHICLE = "app/HomePage/GET_VEHICLE";
export const GET_VEHICLE_SUCCESS = "app/HomePage/GET_VEHICLE_SUCCESS";
export const GET_VEHICLE_ERROR = "app/HomePage/GET_VEHICLE_ERROR";

export const GET_RACE_COURSE = "app/HomePage/GET_RACE_COURSE";
export const GET_RACE_COURSE_SUCCESS = "app/HomePage/GET_RACE_COURSE_SUCCESS";
export const GET_RACE_COURSE_ERROR = "app/HomePage/GET_RACE_COURSE_ERROR";

export const BOOKING_REQUEST = "app/HomePage/BOOKING_REQUEST";
export const BOOKING_REQUEST_SUCCESS = "app/HomePage/BOOKING_REQUEST_SUCCESS";
export const BOOKING_REQUEST_ERROR = "app/HomePage/BOOKING_REQUEST_ERROR";

export const ESTIMATE_PRICE = "app/HomePage/ESTIMATE_PRICE";
export const ESTIMATE_PRICE_SUCCESS = "app/HomePage/ESTIMATE_PRICE_SUCCESS";
export const ESTIMATE_PRICE_ERROR = "app/HomePage/ESTIMATE_PRICE_ERROR";

export const GET_DRIVER_LICENSE = "app/HomePage/GET_DRIVER_LICENSE";
export const GET_DRIVER_LICENSE_SUCCESS = "app/HomePage/GET_DRIVER_LICENSE_SUCCESS";
export const GET_DRIVER_LICENSE_ERROR = "app/HomePage/GET_DRIVER_LICENSE_ERROR";

export const GET_CURRENT_BOOKINGS = "app/HomePage/GET_CURRENT_BOOKINGS";
export const GET_CURRENT_BOOKINGS_SUCCESS = "app/HomePage/GET_CURRENT_BOOKINGS_SUCCESS";
export const GET_CURRENT_BOOKINGS_ERROR = "app/HomePage/GET_CURRENT_BOOKINGS_ERROR";

export const GET_HISTORY_BOOKINGS = "app/HomePage/GET_HISTORY_BOOKINGS";
export const GET_HISTORY_BOOKINGS_SUCCESS = "app/HomePage/GET_HISTORY_BOOKINGS_SUCCESS";
export const GET_HISTORY_BOOKINGS_ERROR = "app/HomePage/GET_HISTORY_BOOKINGS_ERROR";

// JOBS
export const ACT_ACTIVITY = "app/HomePage/ACT_ACTIVITY";
export const ACT_ACTIVITY_SUCCESS = "app/HomePage/ACT_ACTIVITY_SUCCESS";
export const ACT_ACTIVITY_ERROR = "app/HomePage/ACT_ACTIVITY_ERROR";

export const RATING_REVIEW = "app/HomePage/RATING_REVIEW";
export const RATING_REVIEW_SUCCESS = "app/HomePage/RATING_REVIEW_SUCCESS";
export const RATING_REVIEW_ERROR = "app/HomePage/RATING_REVIEW_ERROR";

export const GET_JOB_DETAIL = "app/HomePage/GET_JOB_DETAIL";
export const GET_JOB_DETAIL_SUCCESS = "app/HomePage/GET_JOB_DETAIL_SUCCESS";
export const GET_JOB_DETAIL_ERROR = "app/HomePage/GET_JOB_DETAIL_ERROR";

export const GET_JOB_REQUEST_LIST = "app/HomePage/GET_JOB_REQUEST_LIST";
export const GET_JOB_REQUEST_LIST_SUCCESS = "app/HomePage/GET_JOB_REQUEST_LIST_SUCCESS";
export const GET_JOB_REQUEST_LIST_ERROR = "app/HomePage/GET_JOB_REQUEST_LIST_ERROR";

export const GET_JOB_REQUEST_DETAIL = "app/HomePage/GET_JOB_REQUEST_DETAIL";
export const GET_JOB_REQUEST_DETAIL_SUCCESS = "app/HomePage/GET_JOB_REQUEST_DETAIL_SUCCESS";
export const GET_JOB_REQUEST_DETAIL_ERROR = "app/HomePage/GET_JOB_REQUEST_DETAIL_ERROR";

export const DELETE_JOB_REQUEST = "app/HomePage/DELETE_JOB_REQUEST";
export const DELETE_JOB_REQUEST_SUCCESS = "app/HomePage/DELETE_JOB_REQUEST_SUCCESS";
export const DELETE_JOB_REQUEST_ERROR = "app/HomePage/DELETE_JOB_REQUEST_ERROR";

export const ACCEPT_JOB_REQUEST = "app/HomePage/ACCEPT_JOB_REQUEST";
export const ACCEPT_JOB_REQUEST_SUCCESS = "app/HomePage/ACCEPT_JOB_REQUEST_SUCCESS";
export const ACCEPT_JOB_REQUEST_ERROR = "app/HomePage/ACCEPT_JOB_REQUEST_ERROR";

export const REQUEST_OFFER = "app/HomePage/REQUEST_OFFER";
export const REQUEST_OFFER_SUCCESS = "app/HomePage/REQUEST_OFFER_SUCCESS";
export const REQUEST_OFFER_ERROR = "app/HomePage/REQUEST_OFFER_ERROR";

export const GET_JOB_RECOMMEND_RIDE_LIST = "app/HomePage/GET_JOB_RECOMMEND_RIDE_LIST";
export const GET_JOB_RECOMMEND_RIDE_LIST_SUCCESS = "app/HomePage/GET_JOB_RECOMMEND_RIDE_LIST_SUCCESS";
export const GET_JOB_RECOMMEND_RIDE_LIST_ERROR = "app/HomePage/GET_JOB_RECOMMEND_RIDE_LIST_ERROR";
//------------------------------------------------------------------------------
export const GET_DRIVE_CURRENT_LIST = "app/HomePage/GET_DRIVE_CURRENT_LIST";
export const GET_DRIVE_CURRENT_LIST_SUCCESS = "app/HomePage/GET_DRIVE_CURRENT_LIST_SUCCESS";
export const GET_DRIVE_CURRENT_LIST_ERROR = "app/HomePage/GET_DRIVE_CURRENT_LIST_SUCCESS";

export const GET_DRIVE_HISTORY_LIST = "app/HomePage/GET_DRIVE_HISTORY_LIST";
export const GET_DRIVE_HISTORY_LIST_SUCCESS = "app/HomePage/GET_DRIVE_HISTORY_LIST_SUCCESS";
export const GET_DRIVE_HISTORY_LIST_ERROR = "app/HomePage/GET_DRIVE_HISTORY_LIST_ERROR";

export const GET_DRIVE_BIDDING_LIST = "app/HomePage/GET_DRIVE_BIDDING_LIST";
export const GET_DRIVE_BIDDING_LIST_SUCCESS = "app/HomePage/GET_DRIVE_BIDDING_LIST_SUCCESS";
export const GET_DRIVE_BIDDING_LIST_ERROR = "app/HomePage/GET_DRIVE_BIDDING_LIST_ERROR";

export const GET_OFFER_LIST = "app/HomePage/GET_OFFER_LIST";
export const GET_OFFER_LIST_SUCCESS = "app/HomePage/GET_OFFER_LIST_SUCCESS";
export const GET_OFFER_LIST_ERROR = "app/HomePage/GET_OFFER_LIST_ERROR";

export const GET_DRIVER_VEHICLE_LIST = "app/HomePage/GET_DRIVER_VEHICLE_LIST";
export const GET_DRIVER_VEHICLE_LIST_SUCCESS = "app/HomePage/GET_DRIVER_VEHICLE_LIST_SUCCESS";
export const GET_DRIVER_VEHICLE_LIST_ERROR = "app/HomePage/GET_DRIVER_VEHICLE_LIST_ERROR";

//PAY OUT
export const GET_PAYOUT_COUNTRY = "app/HomePage/GET_PAYOUT_COUNTRY";
export const GET_PAYOUT_COUNTRY_SUCCESS = "app/HomePage/GET_PAYOUT_COUNTRY_SUCCESS";
export const GET_PAYOUT_COUNTRY_ERROR = "app/HomePage/GET_PAYOUT_COUNTRY_ERROR";

export const GET_PAYOUT_STATE = "app/HomePage/GET_PAYOUT_STATE";
export const GET_PAYOUT_STATE_SUCCESS = "app/HomePage/GET_PAYOUT_STATE_SUCCESS";
export const GET_PAYOUT_STATE_ERROR = "app/HomePage/GET_PAYOUT_STATE_ERROR";

export const GET_PAYOUT_CITY = "app/HomePage/GET_PAYOUT_CITY";
export const GET_PAYOUT_CITY_SUCCESS = "app/HomePage/GET_PAYOUT_CITY_SUCCESS";
export const GET_PAYOUT_CITY_ERROR = "app/HomePage/GET_PAYOUT_CITY_ERROR";

export const GET_PAYOUT_ACCOUNT = "app/HomePage/GET_PAYOUT_ACCOUNT";
export const GET_PAYOUT_ACCOUNT_SUCCESS = "app/HomePage/GET_PAYOUT_ACCOUNT_SUCCESS";
export const GET_PAYOUT_ACCOUNT_ERROR = "app/HomePage/GET_PAYOUT_ACCOUNT_ERROR";

export const POST_TRANSACTION = "app/HomePage/POST_TRANSACTION";
export const POST_TRANSACTION_SUCCESS = "app/HomePage/POST_TRANSACTION_SUCCESS";
export const POST_TRANSACTION_ERROR = "app/HomePage/POST_TRANSACTION_ERROR";

// BLOG
export const GET_BLOG_LIST = "app/HomePage/GET_BLOG_LIST";
export const GET_BLOG_LIST_SUCCESS = "app/HomePage/GET_BLOG_LIST_SUCCESS";
export const GET_BLOG_LIST_ERROR = "app/HomePage/GET_BLOG_LIST_ERROR";

export const GET_RELATE_BLOG_LIST = "app/HomePage/GET_RELATE_BLOG_LIST";
export const GET_RELATE_BLOG_LIST_SUCCESS = "app/HomePage/GET_RELATE_BLOG_LIST_SUCCESS";
export const GET_RELATE_BLOG_LIST_ERROR = "app/HomePage/GET_RELATE_BLOG_LIST_ERROR";

export const GET_BLOG_DETAIL = "app/HomePage/GET_BLOG_DETAIL";
export const GET_BLOG_DETAIL_SUCCESS = "app/HomePage/GET_BLOG_DETAIL_SUCCESS";
export const GET_BLOG_DETAIL_ERROR = "app/HomePage/GET_BLOG_DETAIL_ERROR";

// FEATURED DESTINATION
export const GET_FEATURED_LIST = "app/HomePage/GET_FEATURED_LIST";
export const GET_FEATURED_LIST_SUCCESS = "app/HomePage/GET_FEATURED_LIST_SUCCESS";
export const GET_FEATURED_LIST_ERROR = "app/HomePage/GET_FEATURED_LIST_ERROR";

export const GET_FEATURED_DETAIL = "app/HomePage/GET_FEATURED_DETAIL";
export const GET_FEATURED_DETAIL_SUCCESS = "app/HomePage/GET_FEATURED_DETAIL_SUCCESS";
export const GET_FEATURED_DETAIL_ERROR = "app/HomePage/GET_FEATURED_DETAIL_ERROR";

// OTHER PAGES
export const GET_OTHER_PAGE_LIST = "app/HomePage/GET_OTHER_PAGE_LIST";
export const GET_OTHER_PAGE_LIST_SUCCESS = "app/HomePage/GET_OTHER_PAGE_LIST_SUCCESS";
export const GET_OTHER_PAGE_LIST_ERROR = "app/HomePage/GET_OTHER_PAGE_LIST_ERROR";

export const GET_OTHER_PAGE_DETAIL = "app/HomePage/GET_OTHER_PAGE_DETAIL";
export const GET_OTHER_PAGE_DETAIL_SUCCESS = "app/HomePage/GET_OTHER_PAGE_DETAIL_SUCCESS";
export const GET_OTHER_PAGE_DETAIL_ERROR = "app/HomePage/GET_OTHER_PAGE_DETAIL_ERROR";

// PROMOTION
export const GET_PROMOTION_LIST = "app/HomePage/GET_PROMOTION_LIST";
export const GET_PROMOTION_LIST_SUCCESS = "app/HomePage/GET_PROMOTION_LIST_SUCCESS";
export const GET_PROMOTION_LIST_ERROR = "app/HomePage/GET_PROMOTION_LIST_ERROR";

export const GET_TOP_PROMOTION_LIST = "app/HomePage/GET_TOP_PROMOTION_LIST";
export const GET_TOP_PROMOTION_LIST_SUCCESS = "app/HomePage/GET_TOP_PROMOTION_LIST_SUCCESS";
export const GET_TOP_PROMOTION_LIST_ERROR = "app/HomePage/GET_TOP_PROMOTION_LIST_ERROR";

export const GET_PROMOTION_DETAIL = "app/HomePage/GET_PROMOTION_DETAIL";
export const GET_PROMOTION_DETAIL_SUCCESS = "app/HomePage/GET_PROMOTION_DETAIL_SUCCESS";
export const GET_PROMOTION_DETAIL_ERROR = "app/HomePage/GET_PROMOTION_DETAIL_ERROR";

//PAYMENT
export const GET_CREDIT_CARD_CONFIRM = "app/HomePage/GET_CREDIT_CARD_CONFIRM";
export const GET_CREDIT_CARD_CONFIRM_SUCCESS = "app/HomePage/GET_CREDIT_CARD_CONFIRM_SUCCESS";
export const GET_CREDIT_CARD_CONFIRM_ERROR = "app/HomePage/GET_CREDIT_CARD_CONFIRM_ERROR";

export const REQUEST_HELP = "app/HomePage/REQUEST_HELP";
export const REQUEST_HELP_SUCCESS = "app/HomePage/REQUEST_HELP_SUCCESS";
export const REQUEST_HELP_ERROR = "app/HomePage/REQUEST_HELP_ERROR";

//PAYPAL
export const REQUEST_PAYPAL_ORDER = "app/HomePage/REQUEST_PAYPAL_ORDER";
export const REQUEST_PAYPAL_ORDER_SUCCESS = "app/HomePage/REQUEST_PAYPAL_ORDER_SUCCESS";
export const REQUEST_PAYPAL_ORDER_ERROR = "app/HomePage/REQUEST_PAYPAL_ORDER_ERROR";

export const REQUEST_PAYPAL_CAPTURE = "app/HomePage/REQUEST_PAYPAL_CAPTURE";
export const REQUEST_PAYPAL_CAPTURE_SUCCESS = "app/HomePage/REQUEST_PAYPAL_CAPTURE_SUCCESS";
export const REQUEST_PAYPAL_CAPTURE_ERROR = "app/HomePage/REQUEST_PAYPAL_CAPTURE_ERROR";

//TOP BOOKING
export const GET_TOP_BOOKING_LIST = "app/HomePage/GET_TOP_BOOKING_LIST";
export const GET_TOP_BOOKING_LIST_SUCCESS = "app/HomePage/GET_TOP_BOOKING_LIST_SUCCESS";
export const GET_TOP_BOOKING_LIST_ERROR = "app/HomePage/GET_TOP_BOOKING_LIST_ERROR";

//NOTIFICATION
export const GET_NOTIFICATION_LIST = "app/HomePage/GET_NOTIFICATION_LIST";
export const GET_NOTIFICATION_LIST_SUCCESS = "app/HomePage/GET_NOTIFICATION_LIST_SUCCESS";
export const GET_NOTIFICATION_LIST_ERROR = "app/HomePage/GET_NOTIFICATION_LIST_ERROR";

export const READ_NOTIFICATIONS = "app/HomePage/READ_NOTIFICATIONS";
export const READ_NOTIFICATIONS_SUCCESS = "app/HomePage/READ_NOTIFICATIONS_SUCCESS";
export const READ_NOTIFICATIONS_ERROR = "app/HomePage/READ_NOTIFICATIONS_ERROR";

export const DELETE_NOTIFICATIONS = "app/HomePage/DELETE_NOTIFICATIONS";
export const DELETE_NOTIFICATIONS_SUCCESS = "app/HomePage/DELETE_NOTIFICATIONS_SUCCESS";
export const DELETE_NOTIFICATIONS_ERROR = "app/HomePage/DELETE_NOTIFICATIONS_ERROR";

//EARNING
export const GET_STATISTIC_EARNING = "app/HomePage/GET_STATISTIC_EARNING_LIST";
export const GET_STATISTIC_EARNING_SUCCESS = "app/HomePage/GET_STATISTIC_EARNING_LIST_SUCCESS";
export const GET_STATISTIC_EARNING_ERROR = "app/HomePage/GET_STATISTIC_EARNING_LIST_ERROR";

export const GET_TRANSACTION_EARNING_LIST = "app/HomePage/GET_TRANSACTION_EARNING_LIST";
export const GET_TRANSACTION_EARNING_LIST_SUCCESS = "app/HomePage/GET_TRANSACTION_EARNING_LIST_SUCCESS";
export const GET_TRANSACTION_EARNING_LIST_ERROR = "app/HomePage/GET_TRANSACTION_EARNING_LIST_ERROR";

export const GET_REVENUE_CHART = "app/HomePage/GET_REVENUE_CHART";
export const GET_REVENUE_CHART_SUCCESS = "app/HomePage/GET_REVENUE_CHART_SUCCESS";
export const GET_REVENUE_CHART_ERROR = "app/HomePage/GET_REVENUE_CHART_ERROR";
